 linters:
  enable:
    - revive
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gocritic
    - lll
    - prealloc
    - gomnd
    - goconst
    - misspell
    - nakedret
    - unparam
    - tagliatelle
    - bodyclose
    - goerr113
    - wastedassign
    - godot